// apps/web/src/components/predictions/prediction-summary.tsx
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";

export function PredictionSummary({ totalJogos, palpitesPreenchidos }: { totalJogos: number; palpitesPreenchidos: number }) {
  const percentage = Math.round((palpitesPreenchidos / totalJogos) * 100) || 0;

  return (
    <Card>
      <CardContent className="flex flex-wrap items-center justify-between gap-3 pt-6">
        <div>
          <p className="text-sm text-muted-foreground">Progresso dos palpites</p>
          <p className="text-xl font-semibold">
            {palpitesPreenchidos} / {totalJogos}
          </p>
        </div>
        <Badge>{percentage}%</Badge>
      </CardContent>
    </Card>
  );
}

// apps/web/app/components/predictions/PredictionSummary.vue
<script setup lang="ts">
defineProps<{
  totalJogos: number;
  palpitesPreenchidos: number;
}>();
</script>

<template>
  <UCard>
    <div class="flex flex-wrap items-center justify-between gap-3">
      <div>
        <p class="text-sm text-muted">Progresso dos palpites</p>
        <p class="text-xl font-semibold">{{ palpitesPreenchidos }} / {{ totalJogos }}</p>
      </div>
      <UBadge color="primary" variant="subtle">
        {{ Math.round((palpitesPreenchidos / totalJogos) * 100) || 0 }}%
      </UBadge>
    </div>
  </UCard>
</template>
