// apps/web/src/components/predictions/prediction-match-card.tsx
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardFooter, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { Jogo, Palpite, PalpiteUpdate } from "@/components/predictions/types";

const parseGols = (value: string) => {
  if (value === "") return null;
  const parsed = Number(value);
  return Number.isNaN(parsed) ? null : Math.max(0, parsed);
};

export function PredictionMatchCard({ jogo, palpite, onUpdate }: { jogo: Jogo; palpite: Palpite; onUpdate: (payload: PalpiteUpdate) => void }) {
  return (
    <Card>
      <CardHeader>
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div className="text-sm font-medium">{jogo.rodada}</div>
          <div className="text-xs text-muted-foreground">{jogo.horario}</div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="flex items-center justify-between gap-3">
          <div className="min-w-0 flex-1 truncate text-right font-medium">
            {jogo.mandanteEmoji ? <span className="mr-1">{jogo.mandanteEmoji}</span> : null}
            {jogo.mandante}
          </div>
          <Input
            value={palpite.golsMandante ?? ""}
            type="number"
            min="0"
            inputMode="numeric"
            className="w-16"
            disabled={jogo.bloqueado}
            onChange={(event) => onUpdate({ jogoId: jogo.id, lado: "mandante", gols: parseGols(event.target.value) })}
          />
          <span className="text-sm text-muted-foreground">x</span>
          <Input
            value={palpite.golsVisitante ?? ""}
            type="number"
            min="0"
            inputMode="numeric"
            className="w-16"
            disabled={jogo.bloqueado}
            onChange={(event) => onUpdate({ jogoId: jogo.id, lado: "visitante", gols: parseGols(event.target.value) })}
          />
          <div className="min-w-0 flex-1 truncate font-medium">
            {jogo.visitante}
            {jogo.visitanteEmoji ? <span className="ml-1">{jogo.visitanteEmoji}</span> : null}
          </div>
        </div>
      </CardContent>
      <CardFooter className="justify-between gap-2 text-xs text-muted-foreground">
        <span>{[jogo.estadio, jogo.cidade].filter(Boolean).join(" · ") || "Local a definir"}</span>
        {jogo.encerrado ? <Badge variant="secondary">Encerrado</Badge> : jogo.bloqueado ? <Badge variant="warning">Bloqueado</Badge> : <Badge variant="success">Aberto</Badge>}
      </CardFooter>
    </Card>
  );
}

// apps/web/app/components/predictions/PredictionMatchCard.vue
<script setup lang="ts">
type Jogo = {
  id: string;
  rodada: string;
  horario: string;
  estadio: string | null;
  cidade: string | null;
  mandante: string;
  visitante: string;
  mandanteEmoji: string | null;
  visitanteEmoji: string | null;
  encerrado: boolean;
  bloqueado: boolean;
};

type Palpite = {
  golsMandante: number | null;
  golsVisitante: number | null;
};

type PalpiteUpdate = {
  jogoId: string;
  lado: "mandante" | "visitante";
  gols: number | null;
};

const props = defineProps<{
  jogo: Jogo;
  palpite: Palpite;
}>();

const emit = defineEmits<{
  "update-palpite": [payload: PalpiteUpdate];
}>();

const parseGols = (value: string | number | null | undefined) => {
  if (value === null || value === undefined || value === "") {
    return null;
  }

  const parsed = Number(value);
  return Number.isNaN(parsed) ? null : Math.max(0, parsed);
};
</script>

<template>
  <UCard>
    <template #header>
      <div class="flex flex-wrap items-center justify-between gap-2">
        <div class="text-sm font-medium">{{ jogo.rodada }}</div>
        <div class="text-xs text-muted">{{ jogo.horario }}</div>
      </div>
    </template>

    <div class="flex items-center justify-between gap-3">
      <div class="min-w-0 flex-1 text-right font-medium truncate">
        <span v-if="jogo.mandanteEmoji" class="mr-1">{{ jogo.mandanteEmoji }}</span>
        {{ jogo.mandante }}
      </div>
      <UInput
        :model-value="palpite.golsMandante ?? ''"
        type="number"
        min="0"
        inputmode="numeric"
        class="w-16"
        :disabled="jogo.bloqueado"
        @update:model-value="
          emit('update-palpite', {
            jogoId: jogo.id,
            lado: 'mandante',
            gols: parseGols($event),
          })
        "
      />
      <span class="text-sm text-muted">x</span>
      <UInput
        :model-value="palpite.golsVisitante ?? ''"
        type="number"
        min="0"
        inputmode="numeric"
        class="w-16"
        :disabled="jogo.bloqueado"
        @update:model-value="
          emit('update-palpite', {
            jogoId: jogo.id,
            lado: 'visitante',
            gols: parseGols($event),
          })
        "
      />
      <div class="min-w-0 flex-1 font-medium truncate">
        {{ jogo.visitante }}
        <span v-if="jogo.visitanteEmoji" class="ml-1">{{ jogo.visitanteEmoji }}</span>
      </div>
    </div>

    <template #footer>
      <div class="flex flex-wrap items-center justify-between gap-2 text-xs text-muted">
        <span>{{ [jogo.estadio, jogo.cidade].filter(Boolean).join(' · ') || 'Local a definir' }}</span>
        <UBadge v-if="jogo.encerrado" color="neutral" variant="subtle">Encerrado</UBadge>
        <UBadge v-else-if="jogo.bloqueado" color="warning" variant="subtle">Bloqueado</UBadge>
        <UBadge v-else color="success" variant="subtle">Aberto</UBadge>
      </div>
    </template>
  </UCard>
</template>
