// apps/web/src/routes/pools/new.tsx
import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";

import { PageHeader, PageShell } from "@/components/page-shell";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Textarea } from "@/components/ui/textarea";
import { useCreatePoolMutation, usePoolsListQuery } from "@/hooks/use-pools-api";

type Privacidade = "publico" | "privado";
type FormState = { nome: string; campeonato: string; descricao: string; limitePalpite: string; taxaEntrada: number; maxParticipantes: number; privacidade: Privacidade };

const initialForm: FormState = { nome: "", campeonato: "", descricao: "", limitePalpite: "", taxaEntrada: 0, maxParticipantes: 20, privacidade: "publico" };

export const Route = createFileRoute("/pools/new")({ component: NewPoolPage });

function NewPoolPage() {
  const [formulario, setFormulario] = useState<FormState>(initialForm);
  const [erros, setErros] = useState<Record<string, string>>({});
  const [createdSuccessfully, setCreatedSuccessfully] = useState(false);
  const [requestError, setRequestError] = useState<string | null>(null);
  const poolsQuery = usePoolsListQuery();
  const createPoolMutation = useCreatePoolMutation();
  const createdPools = poolsQuery.data ?? [];

  const validar = () => {
    const nextErrors: Record<string, string> = {};
    if (!formulario.nome.trim()) nextErrors.nome = "Informe o nome do bolão.";
    if (!formulario.campeonato.trim()) nextErrors.campeonato = "Informe o campeonato.";
    if (!formulario.limitePalpite) nextErrors.limitePalpite = "Informe a data limite dos palpites.";
    if (formulario.taxaEntrada < 0) nextErrors.taxaEntrada = "A taxa não pode ser negativa.";
    if (formulario.maxParticipantes < 2) nextErrors.maxParticipantes = "O mínimo é 2 participantes.";
    setErros(nextErrors);
    return Object.keys(nextErrors).length === 0;
  };

  const createPool = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setCreatedSuccessfully(false);
    setRequestError(null);
    if (!validar()) return;
    try {
      await createPoolMutation.mutateAsync({ name: formulario.nome.trim() });
      setCreatedSuccessfully(true);
      setFormulario(initialForm);
    } catch (error) {
      setRequestError(error instanceof Error ? error.message : "Erro ao criar bolão.");
    }
  };

  return (
    <div className="min-h-[calc(100vh-64px)] bg-gradient-to-b from-amber-50/60 via-white to-lime-50/40">
      <PageShell className="space-y-6">
        <PageHeader title="Create Pool" description="Configure seu bolão e defina as regras iniciais para os participantes." />
        <Card className="mx-auto w-full max-w-4xl bg-card/80 backdrop-blur-sm">
          <CardContent className="pt-6">
            <form className="space-y-5" onSubmit={createPool}>
              <div className="grid grid-cols-1 items-start gap-4 md:grid-cols-2">
                <Field label="Nome do bolão" error={erros.nome}><Input value={formulario.nome} onChange={(event) => setFormulario({ ...formulario, nome: event.target.value })} placeholder="Ex.: Bolão da Firma" /></Field>
                <Field label="Campeonato" error={erros.campeonato}><Input value={formulario.campeonato} onChange={(event) => setFormulario({ ...formulario, campeonato: event.target.value })} placeholder="Ex.: Brasileirão Série A" /></Field>
              </div>
              <Field label="Descrição (opcional)"><Textarea value={formulario.descricao} onChange={(event) => setFormulario({ ...formulario, descricao: event.target.value })} rows={3} placeholder="Escreva um resumo com regras, prêmios e critérios de desempate." /></Field>
              <div className="grid grid-cols-1 items-start gap-4 md:grid-cols-3">
                <Field label="Data limite do palpite" error={erros.limitePalpite}><Input value={formulario.limitePalpite} onChange={(event) => setFormulario({ ...formulario, limitePalpite: event.target.value })} type="datetime-local" /></Field>
                <Field label="Taxa de entrada (R$)" error={erros.taxaEntrada}><Input value={formulario.taxaEntrada} onChange={(event) => setFormulario({ ...formulario, taxaEntrada: Number(event.target.value) })} type="number" min="0" step="1" /></Field>
                <Field label="Máximo de participantes" error={erros.maxParticipantes}><Input value={formulario.maxParticipantes} onChange={(event) => setFormulario({ ...formulario, maxParticipantes: Number(event.target.value) })} type="number" min="2" step="1" /></Field>
              </div>
              <Field label="Privacidade">
                <RadioGroup value={formulario.privacidade} onValueChange={(value) => setFormulario({ ...formulario, privacidade: value as Privacidade })} className="flex gap-6">
                  <RadioOption value="publico" label="Público" />
                  <RadioOption value="privado" label="Privado" />
                </RadioGroup>
              </Field>
              <div className="flex justify-end"><Button type="submit" disabled={createPoolMutation.isPending}>Criar bolão</Button></div>
            </form>
            {createdSuccessfully ? <Alert className="mt-4" variant="success"><AlertTitle>Bolão criado com sucesso</AlertTitle><AlertDescription>Bolão criado e salvo na API.</AlertDescription></Alert> : null}
            {requestError ? <Alert className="mt-4" variant="destructive"><AlertTitle>Erro ao criar bolão</AlertTitle><AlertDescription>{requestError}</AlertDescription></Alert> : null}
          </CardContent>
        </Card>
        {createdPools.length ? <Card><CardHeader><CardTitle>Bolões cadastrados</CardTitle></CardHeader><CardContent className="space-y-3">{createdPools.map((pool) => <div key={pool.id} className="rounded-lg border p-3"><p className="font-medium">{pool.name}</p><p className="text-sm text-muted-foreground">Criado em: {new Date(pool.createdAt).toLocaleString("pt-BR")}</p></div>)}</CardContent></Card> : null}
        {!createdPools.length && poolsQuery.status === "pending" ? <Alert variant="info"><AlertTitle>Carregando bolões</AlertTitle><AlertDescription>Buscando bolões cadastrados...</AlertDescription></Alert> : null}
        {!createdPools.length && poolsQuery.status === "error" ? <Alert variant="destructive"><AlertTitle>Erro ao carregar bolões</AlertTitle><AlertDescription>{poolsQuery.error?.message || "Não foi possível carregar os bolões."}</AlertDescription></Alert> : null}
      </PageShell>
    </div>
  );
}

function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) {
  return <div className="space-y-2"><Label>{label}</Label>{children}{error ? <p className="text-sm text-destructive">{error}</p> : null}</div>;
}

function RadioOption({ value, label }: { value: string; label: string }) {
  return <div className="flex items-center gap-2"><RadioGroupItem value={value} id={value} /><Label htmlFor={value}>{label}</Label></div>;
}

// apps/web/app/pages/pools/new.vue
<script setup lang="ts">
import { useCreatePoolMutation, usePoolsListQuery } from "~/composables/usePoolsApi";

type Privacidade = "publico" | "privado";

const formulario = reactive({
  nome: "",
  campeonato: "",
  descricao: "",
  limitePalpite: "",
  taxaEntrada: 0,
  maxParticipantes: 20,
  privacidade: "publico" as Privacidade,
});

const erros = reactive<Record<string, string>>({});
const createdSuccessfully = ref(false);
const requestError = ref<string | null>(null);

const opcoesPrivacidade = [
  { label: "Público", value: "publico" as const },
  { label: "Privado", value: "privado" as const },
];

const validar = () => {
  Object.keys(erros).forEach((key) => {
    delete erros[key];
  });

  if (!formulario.nome.trim()) erros.nome = "Informe o nome do bolão.";
  if (!formulario.campeonato.trim()) erros.campeonato = "Informe o campeonato.";
  if (!formulario.limitePalpite) erros.limitePalpite = "Informe a data limite dos palpites.";
  if (formulario.taxaEntrada < 0) erros.taxaEntrada = "A taxa não pode ser negativa.";
  if (formulario.maxParticipantes < 2) erros.maxParticipantes = "O mínimo é 2 participantes.";

  return Object.keys(erros).length === 0;
};

const limparFormulario = () => {
  formulario.nome = "";
  formulario.campeonato = "";
  formulario.descricao = "";
  formulario.limitePalpite = "";
  formulario.taxaEntrada = 0;
  formulario.maxParticipantes = 20;
  formulario.privacidade = "publico";
};

const poolsQuery = usePoolsListQuery();
const createPoolMutation = useCreatePoolMutation();

const createdPools = computed(() => poolsQuery.data.value ?? []);

const createPool = async () => {
  createdSuccessfully.value = false;
  requestError.value = null;
  if (!validar()) return;

  try {
    await createPoolMutation.mutateAsync({
      name: formulario.nome.trim(),
    });
    createdSuccessfully.value = true;
    limparFormulario();
  } catch (error) {
    requestError.value = error instanceof Error ? error.message : "Erro ao criar bolão.";
  }
};
</script>

<template>
  <div
    class="min-h-[calc(100vh-64px)] bg-gradient-to-b from-amber-50/60 via-white to-lime-50/40 dark:from-amber-950/20 dark:via-neutral-950 dark:to-lime-950/20"
  >
    <UContainer class="py-8 space-y-6">
      <UPageHeader
        title="Create Pool"
        description="Configure seu bolão e defina as regras iniciais para os participantes."
        class="rounded-2xl border border-default bg-default/70 p-6 backdrop-blur-sm"
      />

      <UCard class="mx-auto w-full max-w-4xl border-default/80 bg-default/80 backdrop-blur-sm">
        <form class="space-y-5" @submit.prevent="createPool">
          <div class="grid grid-cols-1 items-start gap-4 md:grid-cols-2">
            <UFormField label="Nome do bolão" :error="erros.nome">
              <UInput v-model="formulario.nome" class="w-full" placeholder="Ex.: Bolão da Firma" />
            </UFormField>

            <UFormField label="Campeonato" :error="erros.campeonato">
              <UInput v-model="formulario.campeonato" class="w-full" placeholder="Ex.: Brasileirão Série A" />
            </UFormField>
          </div>

          <UFormField label="Descrição (opcional)">
            <UTextarea
              v-model="formulario.descricao"
              class="w-full"
              :rows="3"
              placeholder="Escreva um resumo com regras, prêmios e critérios de desempate."
            />
          </UFormField>

          <div class="grid grid-cols-1 items-start gap-4 md:grid-cols-3">
            <UFormField label="Data limite do palpite" :error="erros.limitePalpite">
              <UInput v-model="formulario.limitePalpite" class="w-full" type="datetime-local" />
            </UFormField>

            <UFormField label="Taxa de entrada (R$)" :error="erros.taxaEntrada">
              <UInput v-model.number="formulario.taxaEntrada" class="w-full" type="number" min="0" step="1" />
            </UFormField>

            <UFormField label="Máximo de participantes" :error="erros.maxParticipantes">
              <UInput
                v-model.number="formulario.maxParticipantes"
                class="w-full"
                type="number"
                min="2"
                step="1"
              />
            </UFormField>
          </div>

          <UFormField label="Privacidade">
            <URadioGroup
              v-model="formulario.privacidade"
              class="w-full"
              orientation="horizontal"
              :items="opcoesPrivacidade"
            />
          </UFormField>

          <div class="flex items-center justify-end pt-1">
            <UButton type="submit" :loading="createPoolMutation.isPending.value">Criar bolão</UButton>
          </div>
        </form>

        <UAlert
          v-if="createdSuccessfully"
          class="mt-4"
          color="success"
          icon="i-lucide-check-circle"
          title="Bolão criado com sucesso"
          description="Bolão criado e salvo na API."
        />

        <UAlert
          v-if="requestError"
          class="mt-4"
          color="error"
          icon="i-lucide-alert-circle"
          title="Erro ao criar bolão"
          :description="requestError"
        />
      </UCard>

      <UCard v-if="createdPools.length" class="border-default/80 bg-default/80 backdrop-blur-sm">
        <template #header>
          <h2 class="font-semibold">Bolões cadastrados</h2>
        </template>

        <div class="space-y-3">
          <div
            v-for="pool in createdPools"
            :key="pool.id"
            class="rounded-lg border border-default p-3"
          >
            <p class="font-medium">{{ pool.name }}</p>
            <p class="text-sm text-muted">
              Criado em:
              {{ new Date(pool.createdAt).toLocaleString("pt-BR") }}
            </p>
          </div>
        </div>
      </UCard>

      <UAlert
        v-else-if="poolsQuery.status.value === 'pending'"
        color="info"
        icon="i-lucide-loader-2"
        title="Carregando bolões"
        description="Buscando bolões cadastrados..."
      />

      <UAlert
        v-else-if="poolsQuery.status.value === 'error'"
        color="error"
        icon="i-lucide-alert-circle"
        title="Erro ao carregar bolões"
        :description="poolsQuery.error.value?.message || 'Não foi possível carregar os bolões.'"
      />
    </UContainer>
  </div>
</template>
