// apps/web/app/components/predictions/PredictionMatchList.vue
<script setup lang="ts">
import PredictionMatchCard from "~/components/predictions/PredictionMatchCard.vue";

type Jogo = {
  id: number;
  rodada: string;
  horario: string;
  estadio: string;
  mandante: string;
  visitante: string;
};

type Palpite = {
  golsMandante: number | null;
  golsVisitante: number | null;
};

type PalpiteUpdate = {
  jogoId: number;
  lado: "mandante" | "visitante";
  gols: number | null;
};

defineProps<{
  jogos: Jogo[];
  palpites: Record<number, Palpite>;
}>();

const emit = defineEmits<{
  "update-palpite": [payload: PalpiteUpdate];
}>();
</script>

<template>
  <div class="grid gap-4 md:grid-cols-2">
    <PredictionMatchCard
      v-for="jogo in jogos"
      :key="jogo.id"
      :jogo="jogo"
      :palpite="palpites[jogo.id]"
      @update-palpite="emit('update-palpite', $event)"
    />
  </div>
</template>

// apps/web/src/components/predictions/prediction-match-list.tsx
import { PredictionMatchCard } from "@/components/predictions/prediction-match-card";
import type { Jogo, Palpite, PalpiteUpdate } from "@/components/predictions/types";

export function PredictionMatchList({ jogos, palpites, onUpdate }: { jogos: Jogo[]; palpites: Record<string, Palpite>; onUpdate: (payload: PalpiteUpdate) => void }) {
  return (
    <div className="grid gap-4 md:grid-cols-2">
      {jogos.map((jogo) => (
        <PredictionMatchCard key={jogo.id} jogo={jogo} palpite={palpites[jogo.id] ?? { golsMandante: null, golsVisitante: null }} onUpdate={onUpdate} />
      ))}
    </div>
  );
}
